# Generated by Django 5.2.7 on 2025-10-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoemprestimo',
            name='acao',
            field=models.CharField(choices=[('adquirida', 'Adquirida'), ('devolucao', 'Devolução'), ('transferida', 'Transferida')], max_length=20, verbose_name='Ação Realizada'),
        ),
    ]
