# Generated by Django 5.2.7 on 2025-10-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('principal', '0002_alter_historicoemprestimo_acao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='grupo_permissao',
        ),
        migrations.AddField(
            model_name='chave',
            name='grupos_permissao',
            field=models.ManyToManyField(blank=True, help_text='Se definido, apenas usuários deste grupo podem retirar esta chave.', null=True, to='auth.group', verbose_name='Grupo com Permissão'),
        ),
    ]
